### ISSUE TITLE
Livewire v3 Support

### ISSUE THREAD

**Issue by renky** [ralphjsmit/livewire-urls#20]
Since Livewire v3 also has the isLivewireRequest Methot on LivewireManager, I assume that it should just be possible to add Livewire-v3 to the composer.json as an additional Version, which is for now:

```
"livewire/livewire" : "^2.10|^3.0@beta",
```

**Comment by ralphjsmit** [comment]
Thanks @renky, I honestly can't remember getting an email about this issue. Sorry for the delay here then! 
I just merged a PR from @Orrison to support it, so it should now be possible.

**Comment by renky** [comment]
@ralphjsmit hey, thanks a lot... it wasn't urgent, because Livewire 3 is still not usable for me due to too much problems and other packages that doesn't support it yet... so everything is fine...
